name: Test Unit

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies & Test
        run: |
          cd web
          npm install
          npm run test:unit
